vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        recipe_images:
                uri_prefix: /image/recette
                upload_destination: '%kernel.project_dir%/public/images/recette'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
